### ISSUE TITLE
Glyphs Src: weights of masters

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/heebo#1]
@cjdunn @djrrb 

I would like to convert using glyphs2ufo.

In the Glyphs source should the lightest master be named Thin given the weight value?

![Heebo Thin or Light for master 2019-11-06 at 9 49 28 AM](https://user-images.githubusercontent.com/6576107/68308529-ff73a300-007a-11ea-8162-e0670fab3ce4.png)

![Heebo Thin or Light for master 2019-11-06 at 9 49 36 AM](https://user-images.githubusercontent.com/6576107/68308535-026e9380-007b-11ea-80ac-a5be350e6b97.png)

**Comment by cjdunn** [comment]
Yes, lightest should be "Thin" and it looks like the heaviest master should be called "Black". Also you might double check if the default is "Regular" or "Medium" because sometimes this is off as well.

**Comment by cjdunn** [comment]
I've updated these and pushed my changes here:
https://github.com/TypeNetwork/heebo/tree/fea-ufo-conv

There are currently no compatibility issues with this family. I haven't run reports yet so there may be some things to fix there.
