### ISSUE TITLE
missing glyphs/codepoints (micro, onequarter, threequarters, divisionslash)

### ISSUE THREAD

**Issue by moyogo** [TypeNetwork/heebo#3]
FontBakery gives the following fail error:

<summary>🔥 <b>FAIL:</b> Check `Google Fonts Latin Core` glyph coverage.</summary>

* [com.google.fonts/check/glyph_coverage](https://font-bakery.readthedocs.io/en/latest/fontbakery/profiles/googlefonts.html#com.google.fonts/check/glyph_coverage)
<pre>--- Rationale ---

Google Fonts expects that fonts in its collection support at least the minimal
set of characters defined in the `GF-latin-core` glyph-set.

</pre>

* 🔥 **FAIL** Missing required codepoints: 0x00B5 (MICRO SIGN), 0x00BC (VULGAR FRACTION ONE QUARTER), 0x00BD (VULGAR FRACTION ONE HALF), 0x00BE (VULGAR FRACTION THREE QUARTERS) and 0x2215 (DIVISION SLASH) [code: missing-codepoints]

**Comment by pichotta** [comment]
Hi @victoriaalissia    Could you please add these glyphs to the three Heebo sources (Thin, Regular, Black)? In the addGlyphs branch.

divisionslash onehalf onequarter threequarters micro

**Comment by pichotta** [comment]
@moyogo  the missing glyphs have been merged into the master branch
