### ISSUE TITLE
Compare Latin glyphs with latest Roboto

### ISSUE THREAD

**Issue by moyogo** [TypeNetwork/heebo#4]
Is Heebo using the latest Roboto Latin glyphs?

**Comment by pichotta** [comment]
On Mar 23, 2020, at 5:52 PM, Dave Crossland <dcrossland@google.com> wrote:

On Mon, Mar 23, 2020 at 4:34 PM Jill Pichotta <pichotta@typenetwork.com> wrote: 
Question: In Heebo should the Latin outlines be replaced with those from Roboto GF or Classic?

> I had suggested that, thinking they were closer.

 
Question:  Would you like to keep the Heebo latin as it right now?  or further discuss the latin as it relates to Roboto?

> Keeping it as-is is best. 
> 
> Thanks!
>
